services:
  - type: web
    name: trip-planner
    env: node
    rootDir: .
    buildCommand: npm install --prefix client && npm install --prefix server && npm run build --prefix client
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_VERSION
        value: 24.14.0
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
